"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Menu, X } from "lucide-react";
import { useState } from "react";
import Sidebar from "@/components/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-stretch text-black">
          <Sidebar isOpen={isOpen} />

          {/* Hamburger Menu */}
          {/* <button
            onClick={() => setIsOpen(!isOpen)}
            className="md:hidden fixed top-4 left-4 z-50 text-gray-900"
          >
            {isOpen ? <X size={28} /> : <Menu size={28} />}
          </button> */}

          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}
